name = "unityjaeger/quickbounds"
version = "0.3.5"
authors = ["unityjaeger"]
license = "MIT"
repository = "https://github.com/unityjaeger/QuickBounds"

includes = [
  "pesde.toml",
  "README.md",
  "src/**",
]

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "roblox"
lib = "src/main.luau"
build_files = ["src"]