[package]
name = "unityjaeger/quickbounds"
version = "0.3.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
	"lib", 
	"lib/**/*.luau",
	"wally.toml",
	"default.project.json",
]