[package]
name = "unityjaeger/quickbounds"
version = "0.3.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
include = [
	"src",
	"src/**",
	"default.project.json",
	"wally.toml",
	"README.md",
]
exclude = ["**"]